on:
    workflow_dispatch:
    # Triggers the workflow on push or pull request events but only for the master branch
    pull_request:
        branches: [master]

jobs:
    deploy-dev:
        uses: ./.github/workflows/deploy.yaml
        with:
            AZURE_ENV_NAME: dev
            AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        secrets:
            AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}