on:
    workflow_dispatch:
    # Triggers the workflow on push or pull request events but only for the master branch
    pull_request:
        branches: [master]

permissions:
    id-token: write
    contents: read

jobs:
    deploy-dev:
        uses: ./.github/workflows/deploy.yaml
        with:
            AZURE_ENV_NAME: dev
            AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN_DEV }}
            AUTH0_CLIENTID: ${{ vars.AUTH0_CLIENTID_DEV }}
        secrets:
            SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
            SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}