on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    deploy-prod:
        uses: ./.github/workflows/deploy.yaml
        with:
            AZURE_ENV_NAME: prod
            AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        secrets:
            AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}