on:
    workflow_dispatch:
    push:
        branches: [master]

permissions:
    id-token: write
    contents: read

jobs:
    deploy-prod:
        uses: ./.github/workflows/deploy.yaml
        with:
            AZURE_ENV_NAME: prod
            AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN_PROD }}
            AUTH0_CLIENTID: ${{ vars.AUTH0_CLIENTID_PROD }}
        secrets:
            AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}